from pathlib import Path

p = Path('ride2dialysis/index.html')
s = p.read_text(encoding='utf-8')
if 'ride-mobile-dropdowns' in s:
    print('Ride2Dialysis dropdowns already installed.')
    raise SystemExit(0)

old = '<button class="menu" aria-label="Open menu" onclick="document.querySelector(\'.navlinks\').classList.toggle(\'open\')">☰</button>'
new = '<button class="menu" aria-label="Open menu" aria-expanded="false" aria-controls="ride-mobile-dropdowns" onclick="toggleRideMenu(this)">☰</button>'
assert old in s, 'menu button not found'
s = s.replace(old, new, 1)

desktop = '<nav class="navlinks"><a class="active" href="#home">Home</a><a href="#finder">Find a Ride</a><a href="#providers">Providers</a><a href="#cities">Cities</a><a href="#how">How It Works</a><a href="#contact">Contact</a><a class="find-top" href="#finder">⌾&nbsp;&nbsp; Find Providers</a></nav>'
mobile = '''<nav id="ride-mobile-dropdowns" class="ride-mobile-dropdowns" aria-label="Mobile navigation"><div class="ride-nav-group"><button class="ride-nav-toggle" type="button" onclick="toggleRideGroup(this)"><span>Find a Ride</span><span class="ride-chev">▼</span></button><div class="ride-nav-submenu"><button type="button" onclick="rideSelect('service','Recurring Dialysis','#finder')">Recurring Dialysis</button><button type="button" onclick="rideSelect('service','One-Time Ride','#finder')">One-Time Ride</button><button type="button" onclick="rideSelect('service','Companion Assistance','#finder')">Companion Assistance</button><button type="button" onclick="rideSelect('','','#finder')">Search All Rides</button></div></div><div class="ride-nav-group"><button class="ride-nav-toggle" type="button" onclick="toggleRideGroup(this)"><span>Providers</span><span class="ride-chev">▼</span></button><div class="ride-nav-submenu"><button type="button" onclick="rideSelect('','','#providers')">Featured Providers</button><button type="button" onclick="rideSelect('mobility','Wheelchair','#finder')">Wheelchair Providers</button><button type="button" onclick="rideSelect('mobility','Ambulatory','#finder')">Ambulatory Providers</button><button type="button" onclick="rideSelect('mobility','Stretcher','#finder')">Stretcher Providers</button></div></div><div class="ride-nav-group"><button class="ride-nav-toggle" type="button" onclick="toggleRideGroup(this)"><span>Cities</span><span class="ride-chev">▼</span></button><div class="ride-nav-submenu"><button type="button" onclick="rideCity('60601')">Chicago</button><button type="button" onclick="rideCity('60540')">Naperville</button><button type="button" onclick="rideCity('60201')">Evanston</button><button type="button" onclick="rideCity('60173')">Schaumburg</button><button type="button" onclick="rideCity('60505')">Aurora</button></div></div><div class="ride-nav-group"><button class="ride-nav-toggle" type="button" onclick="toggleRideGroup(this)"><span>How It Works</span><span class="ride-chev">▼</span></button><div class="ride-nav-submenu"><button type="button" onclick="rideSelect('','','#finder')">1 · Search Your Area</button><button type="button" onclick="rideSelect('','','#providers')">2 · Compare Providers</button><button type="button" onclick="rideSelect('','','#contact')">3 · Contact Directly</button></div></div><div class="ride-nav-group"><button class="ride-nav-toggle" type="button" onclick="toggleRideGroup(this)"><span>Contact</span><span class="ride-chev">▼</span></button><div class="ride-nav-submenu"><button type="button" onclick="rideSelect('','','#contact')">Contact Information</button><a href="mailto:info@ride2dialysis.com">Email Ride2Dialysis</a><a href="mailto:info@ride2dialysis.com?subject=Provider%20Listing%20Help">Provider Listing Help</a><a href="mailto:info@ride2dialysis.com?subject=Directory%20Question">Directory Questions</a></div></div></nav>'''
assert desktop in s, 'desktop nav not found'
s = s.replace(desktop, desktop + mobile, 1)

anchor = '.menu{display:none;border:1px solid var(--line);border-radius:9px;background:#fff;font-size:22px;padding:6px 10px}'
assert anchor in s, 'menu CSS not found'
s = s.replace(anchor, anchor + '.ride-mobile-dropdowns{display:none}', 1)

mob = '.navlinks{display:none;position:absolute;top:72px;left:0;right:0;background:#fff;padding:12px 22px;border-bottom:1px solid var(--line);flex-direction:column;align-items:stretch}.navlinks.open{display:flex}'
css = '.ride-mobile-dropdowns{display:none;position:absolute;top:72px;left:10px;right:10px;max-height:calc(100vh - 86px);overflow-y:auto;background:#fff;border:1px solid var(--line);border-radius:15px;padding:8px;box-shadow:var(--shadow);z-index:1001}.ride-mobile-dropdowns.open{display:block}.ride-nav-group{border-bottom:1px solid #edf4f6}.ride-nav-group:last-child{border-bottom:0}.ride-nav-toggle{width:100%;border:0;background:#fff;color:var(--navy);text-align:left;padding:14px 12px;border-radius:10px;font-weight:850;font-size:15px;display:flex;align-items:center;justify-content:space-between;gap:12px}.ride-chev{font-size:12px;transition:transform .2s ease}.ride-nav-group.open>.ride-nav-toggle{background:#f1fafb;color:var(--teal-dark)}.ride-nav-group.open .ride-chev{transform:rotate(180deg)}.ride-nav-submenu{display:none;padding:0 6px 8px}.ride-nav-group.open .ride-nav-submenu{display:grid;gap:4px}.ride-nav-submenu button,.ride-nav-submenu a{width:100%;border:0;background:#f7fbfc;color:#31576a;text-align:left;text-decoration:none;padding:11px 14px 11px 20px;border-radius:9px;font-weight:700;font-size:13px}.ride-nav-submenu button:active,.ride-nav-submenu a:active{background:#e7f5f6;color:var(--teal-dark)}'
assert mob in s, 'mobile CSS anchor not found'
s = s.replace(mob, mob + css, 1)

js = '''function toggleRideMenu(btn){const n=document.getElementById('ride-mobile-dropdowns');const o=n.classList.toggle('open');btn.setAttribute('aria-expanded',String(o));if(!o)n.querySelectorAll('.ride-nav-group.open').forEach(g=>g.classList.remove('open'))}\nfunction toggleRideGroup(btn){const g=btn.closest('.ride-nav-group'),o=g.classList.contains('open');document.querySelectorAll('.ride-nav-group.open').forEach(x=>x.classList.remove('open'));if(!o)g.classList.add('open')}\nfunction closeRideMenu(){const n=document.getElementById('ride-mobile-dropdowns');n.classList.remove('open');n.querySelectorAll('.ride-nav-group.open').forEach(g=>g.classList.remove('open'));const b=document.querySelector('.menu[aria-controls="ride-mobile-dropdowns"]');if(b)b.setAttribute('aria-expanded','false')}\nfunction rideSelect(field,value,target){if(field&&value){const e=document.getElementById(field);if(e){for(const o of e.options){if(o.value===value||o.text===value){e.value=o.value||o.text;break}}}}closeRideMenu();const t=document.querySelector(target);if(t)setTimeout(()=>t.scrollIntoView({behavior:'smooth',block:'start'}),40)}\nfunction rideCity(zip){const e=document.getElementById('zip');if(e)e.value=zip;rideSelect('','','#finder')}\ndocument.querySelectorAll('#ride-mobile-dropdowns a').forEach(a=>a.addEventListener('click',closeRideMenu));\n'''
marker = "document.getElementById('finder').addEventListener('submit',e=>{"
assert marker in s, 'script anchor not found'
s = s.replace(marker, js + marker, 1)
p.write_text(s, encoding='utf-8')
print('Ride2Dialysis mobile dropdowns installed.')
