from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')

css_anchor = ".tag{background:#e6f5f6;color:#0b7180;padding:5px 8px;border-radius:999px;font-size:12px}"
css_extra = css_anchor + ".provider-actions,.result-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.provider-actions a,.provider-actions button,.result-actions a,.result-actions button{border:0;border-radius:10px;padding:10px 12px;font-size:13px;font-weight:800;text-decoration:none;cursor:pointer}.btn-primary{background:var(--teal);color:#fff}.btn-secondary{background:#eef8fa;color:var(--navy);border:1px solid var(--line)!important}.ride-form{display:grid;gap:12px;margin-top:12px}.ride-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ride-form label{display:grid;gap:6px;font-size:13px;font-weight:800;color:var(--navy)}.ride-form input,.ride-form select,.ride-form textarea{width:100%;border:1px solid #c9dce2;border-radius:11px;padding:11px 12px;background:#fff;color:#29495c;font-size:15px}.ride-form textarea{min-height:88px;resize:vertical}.ride-submit{border:0;border-radius:11px;background:var(--teal);color:#fff;padding:13px 15px;font-weight:900;font-size:15px}.ride-note{font-size:12px;color:var(--muted);line-height:1.45}.provider-meta{font-size:13px;color:var(--muted);line-height:1.5}"
if '.ride-form{' not in s:
    s = s.replace(css_anchor, css_extra, 1)

mobile_anchor = "  .dialysis{margin:0 14px 32px;padding:22px;border-radius:20px;background:linear-gradient(135deg,#075c70,#0794a5);color:#fff}"
if '  .ride-grid{grid-template-columns:1fr}' not in s:
    s = s.replace(mobile_anchor, "  .ride-grid{grid-template-columns:1fr}\n" + mobile_anchor, 1)

old_feature = "function renderFeaturedProviders(){const box=document.querySelector('.provider-list');if(!box||!providers.length)return;box.innerHTML=providers.slice(0,3).map((p,i)=>`<article class=\"provider\"><div class=\"provider-top\"><div><h3>${p.name}</h3><div class=\"city\">${p.city}, ${p.state} ${p.zip||''}</div></div><button class=\"view\" onclick=\"showProvider(${i})\">View</button></div><div class=\"smalltags\"><span>NEMT</span><span>Medical Transport Van</span></div></article>`).join('')}"
new_feature = "function renderFeaturedProviders(){const box=document.querySelector('.provider-list');if(!box||!providers.length)return;box.innerHTML=providers.slice(0,3).map((p,i)=>`<article class=\"provider\"><div class=\"provider-top\"><div><h3>${p.name}</h3><div class=\"city\">${p.city}, ${p.state} ${p.zip||''}</div></div></div><div class=\"smalltags\"><span>NEMT</span><span>Medical Transport Van</span></div><div class=\"provider-actions\"><button class=\"btn-secondary\" onclick=\"showProvider(${i})\">View Provider</button>${p.phone?`<a class=\"btn-secondary\" href=\"tel:${p.phone}\">Call Provider</a>`:''}<button class=\"btn-primary\" onclick=\"requestRideByNpi('${p.npi}')\">Request a Ride</button></div></article>`).join('')}"
s = s.replace(old_feature, new_feature, 1)

old_show = "function showProvider(i){const p=providers[i];openModal(p.name,`<p>${p.city}</p><div class=\"tags\">${p.tags.map(t=>`<span class=\"tag\">${t}</span>`).join('')}</div><p style=\"margin-top:14px\">Contact the provider directly to verify availability, pricing, credentials, and scheduling.</p>`)}`"
new_show = "function showProvider(i){const p=providers[i];showProviderRecord(p)}\nfunction showProviderRecord(p){openModal(p.name,`<div class=\"provider-meta\">${p.address1||''}${p.address2?' '+p.address2:''}<br>${p.city}, ${p.state} ${p.zip||''}${p.phone?`<br>${p.phone}`:''}<br>NPI: ${p.npi||''}</div><div class=\"tags\" style=\"margin-top:10px\">${(p.tags||[]).map(t=>`<span class=\"tag\">${t}</span>`).join('')}</div><div class=\"provider-actions\">${p.phone?`<a class=\"btn-secondary\" href=\"tel:${p.phone}\">Call Provider</a>`:''}<button class=\"btn-primary\" onclick=\"requestRideByNpi('${p.npi}')\">Request a Ride</button></div><p class=\"ride-note\" style=\"margin-top:14px\">Verify service area, availability, pricing, credentials, and trip acceptance with the provider.</p>`)}`"
s = s.replace(old_show, new_show, 1)

old_render = "function renderProviderList(list){return `<div class=\"results\">${list.map(p=>`<div class=\"result\"><h3>${p.name}</h3><p>${p.city}, ${p.state} ${p.zip||''}${p.phone?`<br><a href=\"tel:${p.phone}\">${p.phone}</a>`:''}</p><div class=\"tags\">${p.tags.map(t=>`<span class=\"tag\">${t}</span>`).join('')}</div></div>`).join('')}</div>`}"
new_render = "function renderProviderList(list){return `<div class=\"results\">${list.map(p=>`<div class=\"result\"><h3>${p.name}</h3><p>${p.city}, ${p.state} ${p.zip||''}${p.phone?`<br>${p.phone}`:''}</p><div class=\"tags\">${(p.tags||[]).map(t=>`<span class=\"tag\">${t}</span>`).join('')}</div><div class=\"result-actions\"><button class=\"btn-secondary\" onclick=\"showProviderByNpi('${p.npi}')\">View Provider</button>${p.phone?`<a class=\"btn-secondary\" href=\"tel:${p.phone}\">Call Provider</a>`:''}<button class=\"btn-primary\" onclick=\"requestRideByNpi('${p.npi}')\">Request a Ride</button></div></div>`).join('')}</div>`}"
s = s.replace(old_render, new_render, 1)

if 'function requestRideByNpi' not in s:
    helpers = r'''function findProviderByNpi(npi){return providers.find(p=>String(p.npi)===String(npi))}
function showProviderByNpi(npi){const p=findProviderByNpi(npi);if(p)showProviderRecord(p)}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function requestRideByNpi(npi){const p=findProviderByNpi(npi);if(!p)return;const service=document.getElementById('mService')?.value||'';const access=document.getElementById('mAccessibility')?.value||'';openModal('Request a Ride',`<p class="provider-meta"><b>${p.name}</b><br>${p.city}, ${p.state} ${p.zip||''}${p.phone?`<br>${p.phone}`:''}</p><form class="ride-form" id="rideRequestForm"><input type="hidden" name="provider" value="${escapeHtml(p.name)}"><input type="hidden" name="npi" value="${escapeHtml(p.npi||'')}"><div class="ride-grid"><label>Passenger Name<input name="passenger" required autocomplete="name"></label><label>Phone Number<input name="phone" required inputmode="tel" autocomplete="tel"></label></div><label>Pickup Address<input name="pickup" required autocomplete="street-address"></label><label>Destination<input name="destination" required></label><div class="ride-grid"><label>Appointment Date<input type="date" name="date" required></label><label>Pickup / Appointment Time<input type="time" name="time" required></label></div><div class="ride-grid"><label>Trip Type<select name="trip"><option>Round Trip</option><option>One Way</option></select></label><label>Mobility / Service<select name="mobility"><option>${escapeHtml(service||access||'Ambulatory')}</option><option>Wheelchair</option><option>Ambulatory</option><option>Stretcher</option><option>Dialysis</option><option>Companion Assistance</option></select></label></div><label>Special Instructions<textarea name="notes" placeholder="Wheelchair size, stairs, oxygen, return-time details, escort needs, etc."></textarea></label><button class="ride-submit" type="submit">Send Ride Request</button><div class="ride-note">This sends a ride-request inquiry through Eazy Medical Transportation. The ride is not confirmed until the selected provider accepts it.</div></form>`);setTimeout(()=>{const f=document.getElementById('rideRequestForm');if(f)f.addEventListener('submit',submitRideRequest)},0)}
function submitRideRequest(e){e.preventDefault();const f=e.currentTarget;const d=Object.fromEntries(new FormData(f).entries());const subject=`Ride Request - ${d.provider}`;const body=[`Provider: ${d.provider}`,`Provider NPI: ${d.npi}`,`Passenger: ${d.passenger}`,`Phone: ${d.phone}`,`Pickup: ${d.pickup}`,`Destination: ${d.destination}`,`Date: ${d.date}`,`Time: ${d.time}`,`Trip: ${d.trip}`,`Mobility/Service: ${d.mobility}`,`Notes: ${d.notes||''}`].join('\n');window.location.href=`mailto:info@eazymedicaltransportation.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;openModal('Ride Request Ready',`<p>Your ride-request details have been prepared for Eazy Medical Transportation.</p><p class="ride-note">The selected provider must still confirm availability and accept the trip.</p>`)}
'''
    s = s.replace("function showProviderCategory(tag){", helpers + "function showProviderCategory(tag){", 1)

s = s.replace('<h2>Featured Providers</h2><p>Examples displayed in the directory.</p>', '<h2>Featured Providers</h2><p>Choose a provider, call directly, or send a ride request.</p>', 1)
s = s.replace('<article class="step"><div class="num">3</div><div><h3>Verify directly</h3><p>Confirm availability, pricing, credentials, and scheduling directly.</p></div></article>', '<article class="step"><div class="num">3</div><div><h3>Request your ride</h3><p>Choose a provider and send trip details for confirmation.</p></div></article>', 1)

p.write_text(s, encoding='utf-8')
print('Ride request flow installed')
