from pathlib import Path
import re

p = Path('index.html')
s = p.read_text(encoding='utf-8')

css_anchor = ".provider-meta{font-size:13px;color:var(--muted);line-height:1.5}"
css_extra = css_anchor + ".claim-badge{display:inline-flex;align-items:center;gap:5px;background:#e3f7ef;color:#176348;border:1px solid #bde8d7;border-radius:999px;padding:5px 8px;font-size:11px;font-weight:900}.claim-link{background:#fff;color:var(--teal);border:1px solid #9fd5dc!important}.claim-form{display:grid;gap:12px;margin-top:12px}.claim-form label{display:grid;gap:6px;font-size:13px;font-weight:800}.claim-form input,.claim-form select,.claim-form textarea{width:100%;border:1px solid #c9dce2;border-radius:11px;padding:11px 12px;background:#fff;color:#29495c;font-size:15px}.claim-form textarea{min-height:84px;resize:vertical}.claim-callout{background:#f3fafb;border:1px solid var(--line);border-radius:12px;padding:12px;font-size:12px;line-height:1.5;color:var(--muted);margin:10px 0}.provider-routing{font-size:12px;color:#176348;font-weight:800;margin-top:8px}"
if '.claim-badge{' not in s:
    s = s.replace(css_anchor, css_extra, 1)

# Add Provider Sign Up to mobile Providers dropdown.
nav_anchor = '<button onclick="goTo(\'providers\')">Featured Providers</button>'
if 'openProviderSignup()' not in s:
    s = s.replace(nav_anchor, nav_anchor + '\n        <button onclick="openProviderSignup()">Provider Sign Up / Claim Listing</button>', 1)

# Load claim routing data and merge by NPI.
s = re.sub(
    r"let providers=\[\];\nasync function loadProviders\(\)\{.*?\}\nfunction renderFeaturedProviders",
    "let providers=[];\nasync function loadProviders(){try{const [r,cr]=await Promise.all([fetch('providers-il.json?v=2',{cache:'no-store'}),fetch('providers-claimed.json?v=1',{cache:'no-store'})]);const d=await r.json();let claims={};if(cr.ok){const cd=await cr.json();claims=cd.claims||{}}providers=(d.providers||[]).map(p=>Object.assign({},p,claims[String(p.npi)]||{}));renderFeaturedProviders();}catch(e){console.error('Provider database failed to load',e)}}\nfunction renderFeaturedProviders",
    s,
    count=1,
    flags=re.S,
)

# Featured cards.
new_feature = '''function renderFeaturedProviders(){const box=document.querySelector('.provider-list');if(!box||!providers.length)return;box.innerHTML=providers.slice(0,3).map((p,i)=>`<article class="provider"><div class="provider-top"><div><h3>${p.name}</h3><div class="city">${p.city}, ${p.state} ${p.zip||''}</div>${p.claimed?'<span class="claim-badge">✓ Claimed Provider</span>':''}</div></div><div class="smalltags"><span>NEMT</span><span>Medical Transport Van</span></div><div class="provider-actions"><button class="btn-secondary" onclick="showProvider(${i})">View Provider</button>${p.phone?`<a class="btn-secondary" href="tel:${p.phone}">Call Provider</a>`:''}<button class="btn-primary" onclick="requestRideByNpi('${p.npi}')">Request a Ride</button>${p.claimed?'':`<button class="claim-link" onclick="claimProviderByNpi('${p.npi}')">Claim This Provider</button>`}</div></article>`).join('')}'''
s = re.sub(r"function renderFeaturedProviders\(\)\{.*?\}\nfunction toggleNav", new_feature + "\nfunction toggleNav", s, count=1, flags=re.S)

# Provider profile function (also fixes the previously incomplete View Provider path).
s = re.sub(
    r"function showProvider\(i\)\{.*?\}\nfunction renderProviderList",
    '''function showProvider(i){const p=providers[i];if(p)showProviderRecord(p)}
function showProviderRecord(p){openModal(p.name,`<div class="provider-meta">${p.address1||''}${p.address2?' '+p.address2:''}<br>${p.city}, ${p.state} ${p.zip||''}${p.phone?`<br>${p.phone}`:''}<br>NPI: ${p.npi||''}</div>${p.claimed?'<div style="margin-top:10px"><span class="claim-badge">✓ Claimed Provider</span></div>':''}<div class="tags" style="margin-top:10px">${(p.tags||[]).map(t=>`<span class="tag">${t}</span>`).join('')}</div>${p.claimed&&p.serviceArea?`<p class="provider-meta"><b>Service area:</b> ${escapeHtml(p.serviceArea)}</p>`:''}${p.claimed&&p.services?`<p class="provider-meta"><b>Services:</b> ${escapeHtml(p.services)}</p>`:''}<div class="provider-actions">${p.phone?`<a class="btn-secondary" href="tel:${p.phone}">Call Provider</a>`:''}<button class="btn-primary" onclick="requestRideByNpi('${p.npi}')">Request a Ride</button>${p.claimed?'':`<button class="claim-link" onclick="claimProviderByNpi('${p.npi}')">Claim This Provider</button>`}</div>${p.claimed&&p.acceptsOnlineRequests&&p.dispatchEmail?'<div class="provider-routing">Ride requests are routed directly to this provider.</div>':'<p class="ride-note" style="margin-top:14px">Ride requests are inquiries only until the provider accepts and confirms the trip.</p>'}`)}
function renderProviderList''',
    s,
    count=1,
    flags=re.S,
)

new_render = '''function renderProviderList(list){return `<div class="results">${list.map(p=>`<div class="result"><h3>${p.name}</h3><p>${p.city}, ${p.state} ${p.zip||''}${p.phone?`<br>${p.phone}`:''}</p>${p.claimed?'<span class="claim-badge">✓ Claimed Provider</span>':''}<div class="tags" style="margin-top:8px">${(p.tags||[]).map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="result-actions"><button class="btn-secondary" onclick="showProviderByNpi('${p.npi}')">View Provider</button>${p.phone?`<a class="btn-secondary" href="tel:${p.phone}">Call Provider</a>`:''}<button class="btn-primary" onclick="requestRideByNpi('${p.npi}')">Request a Ride</button>${p.claimed?'':`<button class="claim-link" onclick="claimProviderByNpi('${p.npi}')">Claim This Provider</button>`}</div></div>`).join('')}</div>`}'''
s = re.sub(r"function renderProviderList\(list\)\{.*?\}\nfunction findProviderByNpi", new_render + "\nfunction findProviderByNpi", s, count=1, flags=re.S)

claim_helpers = r'''function openProviderSignup(){closeMobileNav();openProviderClaimForm(null)}
function claimProviderByNpi(npi){const p=findProviderByNpi(npi);openProviderClaimForm(p||null)}
function openProviderClaimForm(p){const name=p?.name||'';const npi=p?.npi||'';openModal(p?'Claim This Provider':'Provider Sign Up',`<div class="claim-callout">Claiming a listing allows a verified provider to receive Eazy ride requests directly. Eazy will verify the business before activating direct routing.</div><form class="claim-form" id="providerClaimForm"><label>Business / Provider Name<input name="provider" required value="${escapeHtml(name)}"></label><label>NPI<input name="npi" inputmode="numeric" value="${escapeHtml(npi)}" placeholder="10-digit NPI"></label><div class="ride-grid"><label>Contact Name<input name="contact" required autocomplete="name"></label><label>Title / Role<input name="title" required placeholder="Owner, Dispatcher, Manager"></label></div><div class="ride-grid"><label>Dispatch Email<input type="email" name="dispatchEmail" required autocomplete="email"></label><label>Dispatch Phone<input name="dispatchPhone" required inputmode="tel" autocomplete="tel"></label></div><label>Website<input name="website" type="url" placeholder="https://"></label><label>Service Area<textarea name="serviceArea" required placeholder="Cities, counties, or ZIP codes served"></textarea></label><label>Transportation Services<textarea name="services" required placeholder="Wheelchair, ambulatory, dialysis, stretcher, companion, etc."></textarea></label><label>Accept ride requests from Eazy?<select name="accepts"><option value="Yes">Yes — send ride requests directly to our dispatch team</option><option value="No">No — claim listing only</option></select></label><button class="ride-submit" type="submit">Submit Provider Claim</button><div class="ride-note">Submitting a claim does not automatically activate the listing. Eazy will verify the provider before direct request routing is turned on.</div></form>`);setTimeout(()=>{const f=document.getElementById('providerClaimForm');if(f)f.addEventListener('submit',submitProviderClaim)},0)}
function submitProviderClaim(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const subject=`Provider Claim - ${d.provider}`;const body=[`Provider: ${d.provider}`,`NPI: ${d.npi||''}`,`Contact: ${d.contact}`,`Title: ${d.title}`,`Dispatch Email: ${d.dispatchEmail}`,`Dispatch Phone: ${d.dispatchPhone}`,`Website: ${d.website||''}`,`Service Area: ${d.serviceArea}`,`Services: ${d.services}`,`Accept Eazy Ride Requests: ${d.accepts}`].join('\n');window.location.href=`mailto:info@eazymedicaltransportation.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;openModal('Provider Claim Ready',`<p>Your provider claim has been prepared for Eazy Medical Transportation.</p><p class="ride-note">After verification, the provider can be marked as claimed and ride requests can be routed directly to its dispatch contact.</p>`)}
'''
if 'function openProviderSignup' not in s:
    s = s.replace('function findProviderByNpi', claim_helpers + 'function findProviderByNpi', 1)

# Replace ride request form to clearly show direct routing status.
new_request = r'''function requestRideByNpi(npi){const p=findProviderByNpi(npi);if(!p)return;const service=document.getElementById('mService')?.value||'';const access=document.getElementById('mAccessibility')?.value||'';const direct=!!(p.claimed&&p.acceptsOnlineRequests&&p.dispatchEmail);openModal('Request a Ride',`<p class="provider-meta"><b>${p.name}</b><br>${p.city}, ${p.state} ${p.zip||''}${p.phone?`<br>${p.phone}`:''}</p>${direct?'<div class="provider-routing">✓ This request will be routed directly to the provider\'s dispatch team.</div>':'<div class="claim-callout">This provider has not activated direct Eazy dispatch routing yet. Your request will be sent through Eazy for follow-up.</div>'}<form class="ride-form" id="rideRequestForm"><input type="hidden" name="provider" value="${escapeHtml(p.name)}"><input type="hidden" name="npi" value="${escapeHtml(p.npi||'')}"><div class="ride-grid"><label>Passenger Name<input name="passenger" required autocomplete="name"></label><label>Phone Number<input name="phone" required inputmode="tel" autocomplete="tel"></label></div><label>Pickup Address<input name="pickup" required autocomplete="street-address"></label><label>Destination<input name="destination" required></label><div class="ride-grid"><label>Appointment Date<input type="date" name="date" required></label><label>Pickup / Appointment Time<input type="time" name="time" required></label></div><div class="ride-grid"><label>Trip Type<select name="trip"><option>Round Trip</option><option>One Way</option></select></label><label>Mobility / Service<select name="mobility"><option>${escapeHtml(service||access||'Ambulatory')}</option><option>Wheelchair</option><option>Ambulatory</option><option>Stretcher</option><option>Dialysis</option><option>Companion Assistance</option></select></label></div><label>Special Instructions<textarea name="notes" placeholder="Wheelchair size, stairs, oxygen, return-time details, escort needs, etc."></textarea></label><button class="ride-submit" type="submit">Send Ride Request</button><div class="ride-note">The ride is not confirmed until the provider accepts the request and confirms the trip.</div></form>`);setTimeout(()=>{const f=document.getElementById('rideRequestForm');if(f)f.addEventListener('submit',submitRideRequest)},0)}'''
s = re.sub(r"function requestRideByNpi\(npi\)\{.*?\}\nfunction submitRideRequest", new_request + "\nfunction submitRideRequest", s, count=1, flags=re.S)

new_submit = r'''function submitRideRequest(e){e.preventDefault();const f=e.currentTarget;const d=Object.fromEntries(new FormData(f).entries());const p=findProviderByNpi(d.npi);const direct=!!(p&&p.claimed&&p.acceptsOnlineRequests&&p.dispatchEmail);const target=direct?p.dispatchEmail:'info@eazymedicaltransportation.com';const subject=`Ride Request - ${d.provider}`;const body=[`Provider: ${d.provider}`,`Provider NPI: ${d.npi}`,`Passenger: ${d.passenger}`,`Phone: ${d.phone}`,`Pickup: ${d.pickup}`,`Destination: ${d.destination}`,`Date: ${d.date}`,`Time: ${d.time}`,`Trip: ${d.trip}`,`Mobility/Service: ${d.mobility}`,`Notes: ${d.notes||''}`,`Submitted via: EazyMedicalTransportation.com`].join('\n');window.location.href=`mailto:${encodeURIComponent(target)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;openModal('Ride Request Ready',`<p>${direct?'Your request has been prepared to send directly to '+escapeHtml(d.provider)+' dispatch.':'Your request has been prepared for Eazy Medical Transportation to route.'}</p><p class="ride-note">The selected provider must still confirm availability and accept the trip.</p>`)}`'''
s = re.sub(r"function submitRideRequest\(e\)\{.*?\}\nfunction showProviderCategory", new_submit + "\nfunction showProviderCategory", s, count=1, flags=re.S)

# Add a provider CTA above footer on mobile.
cta = '''<section class="section alt" id="provider-signup"><h2>Are you a transportation provider?</h2><p>Claim your listing, add your service area, and receive ride requests directly from Eazy.</p><button class="ride-submit" type="button" onclick="openProviderSignup()">Claim or Register Your Provider</button></section>\n\n'''
if 'id="provider-signup"' not in s:
    s = s.replace('<section class="dialysis">', cta + '<section class="dialysis">', 1)

p.write_text(s, encoding='utf-8')
print('provider claim layer applied')
