#!/usr/bin/env python3
import json,re,html
from collections import Counter
from pathlib import Path
ROOT=Path('.')
BASE='https://eazymedicaltransportation.com'
SITEMAP=ROOT/'sitemap.xml'
PRIORITY_CITIES=['CHICAGO','SCHAUMBURG','WAUKEGAN','NAPERVILLE','EVANSTON','SKOKIE','DES PLAINES','ARLINGTON HEIGHTS','ELGIN','AURORA']
GUIDES={
'how-nemt-works':('How Non-Emergency Medical Transportation Works','A practical explanation of NEMT, who uses it, how trips are arranged, and what riders should confirm before scheduling.',[('What is NEMT?','Non-emergency medical transportation helps people reach scheduled healthcare when an ambulance is not required. Trips may include physician visits, dialysis, therapy, outpatient procedures and other planned care.'),('How are rides arranged?','Depending on the rider and payer, transportation may be arranged directly with a provider, through a managed-care plan, transportation broker, facility, caregiver or private-pay booking.'),('What should I confirm?','Confirm pickup location, appointment time, mobility needs, return-trip procedure, service area, payment arrangements and whether an escort or special assistance is required.')]),
'medicaid-nemt-guide':('Medicaid and Non-Emergency Medical Transportation','Understand how Medicaid transportation commonly works and what information riders should verify with their plan or transportation provider.',[('Does every Medicaid plan work the same way?','No. Medicaid transportation rules and scheduling procedures vary by state and managed-care plan. Riders should confirm eligibility and authorization requirements with the applicable program.'),('Should recurring rides be scheduled ahead?','Often yes. Recurring treatments and long-distance trips may require advance scheduling. Keep appointment details, member information and mobility needs available when arranging transportation.'),('Does an Eazy listing prove Medicaid participation?','No. A directory listing does not establish Medicaid participation. Confirm network status and authorization directly with the plan, broker or provider.')]),
'medicare-transportation-guide':('Medicare Transportation: What to Know','A plain-language guide to Medicare transportation, Medicare Advantage transportation benefits and the difference from Medicaid NEMT.',[('Does Original Medicare routinely cover non-emergency rides?','Routine non-emergency rides are not generally a standard Original Medicare transportation benefit. Coverage circumstances differ from emergency or medically necessary ambulance services.'),('Can Medicare Advantage include transportation?','Some Medicare Advantage plans may include transportation benefits. The member should verify limits, eligible destinations and scheduling procedures with the plan.'),('What should I verify before booking?','Ask who is responsible for payment and whether prior authorization or use of a designated transportation network is required.')]),
'wheelchair-transportation-guide':('Wheelchair Transportation Guide','How to compare wheelchair-accessible NEMT providers and prepare for a medical transportation trip.',[('What wheelchair details should I provide?','Tell the provider the wheelchair type, approximate dimensions, passenger weight if relevant, and whether the rider can transfer from the chair.'),('What assistance level should I ask about?','Ask whether service is curb-to-curb, door-to-door or includes additional assistance. Explain stairs, ramps, elevators and oxygen or equipment needs.'),('How are return trips handled?','Medical appointments may run late. Confirm how return pickups are handled and who to contact if the appointment schedule changes.')]),
'dialysis-transportation-guide':('Dialysis Transportation Guide','How to plan recurring transportation to dialysis and reduce missed or delayed trips.',[('Why are recurring schedules important?','Dialysis often occurs multiple times each week, making consistent pickup windows and provider communication especially important.'),('What if treatment end times vary?','Ask whether the provider waits, uses a will-call return, or schedules a flexible pickup window.'),('Should I have a backup plan?','Keep provider and facility contact information available and understand the procedure if a driver is delayed or a treatment schedule changes.')]),
'hospital-discharge-transportation':('Hospital Discharge Transportation','What families and care teams should consider when arranging non-emergency transportation after a hospital discharge.',[('How do I match the vehicle to the patient?','Confirm whether the passenger can walk, needs a wheelchair-accessible vehicle, requires a stretcher-capable service or needs other assistance.'),('How should discharge timing be handled?','Discharge times can shift. Confirm how the provider handles delays and whether the facility requires a specific pickup location.'),('What should be ready at the destination?','Make sure someone can receive the passenger if needed and that stairs, ramps, elevators or mobility equipment at the destination are considered.')]),
'how-to-choose-a-nemt-provider':('How to Choose a Non-Emergency Medical Transportation Provider','Questions to ask when comparing NEMT providers for yourself, a family member or a patient.',[('What service-area questions should I ask?','Confirm that the provider serves both the pickup and destination and can handle one-time or recurring trips.'),('How do I verify accessibility?','Describe mobility needs in detail and verify the vehicle and assistance level before scheduling.'),('What payment and scheduling terms matter?','Ask about rates or benefits, cancellation rules, scheduling lead time, return-trip procedures and how to reach dispatch on the day of travel.')]),
'private-pay-medical-transportation':('Private-Pay Medical Transportation','When private-pay NEMT may be useful and what to ask before paying for a ride.',[('When is private-pay transportation used?','Families may choose private-pay transportation when insurance does not cover the trip, when a preferred provider is out of network, or when a faster scheduling option is needed.'),('What should a quote include?','Ask whether the quote includes mileage, wait time, wheelchair service, assistance, tolls and the return trip.'),('What cancellation terms matter?','Understand deposits, cancellation windows and charges if an appointment runs longer than expected.')]),
'recurring-medical-rides':('Recurring Medical Transportation','A guide to organizing repeat rides for dialysis, therapy, rehabilitation and other ongoing care.',[('What belongs in a master schedule?','Provide treatment days, appointment times, pickup address, facility address and any recurring mobility needs.'),('Why use consistent contacts?','Keep the same rider, caregiver, facility and dispatch contact information whenever possible.'),('What changes should be reconfirmed?','Reconfirm holidays, treatment schedule changes and transportation authorizations before they become missed trips.')]),
'nemt-checklist':('NEMT Ride Scheduling Checklist','A simple checklist of information to have ready before contacting a medical transportation provider.',[('What trip details should I have ready?','Pickup address, destination, appointment date and time, one-way or round-trip status and expected return timing.'),('What passenger needs should I describe?','Wheelchair or ambulatory status, transfer ability, stairs, oxygen or equipment, escort needs and any assistance requirements.'),('What payment information may be needed?','Insurance or plan information when applicable, authorization number if required, or private-pay pricing and payment method.')])}
STYLE='''body{margin:0;font-family:Arial,sans-serif;color:#153a56;background:#f7fbfc}header{background:#087f91;color:#fff;text-align:center;padding:11px 18px;font-weight:700;font-size:13px}nav{background:#fff;border-bottom:1px solid #d7e7eb;padding:18px 6%;display:flex;gap:24px;flex-wrap:wrap}nav a{color:#0b3552;text-decoration:none;font-weight:700}main{max-width:980px;margin:auto;padding:48px 22px 70px}h1{font-size:42px;line-height:1.08;margin:0 0 16px}h2{margin-top:34px}p,li{font-size:17px;line-height:1.7;color:#4c6676}.card{background:#fff;border:1px solid #d7e7eb;border-radius:16px;padding:24px;margin:22px 0}.links,.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.links a,.actions a{background:#087f91;color:#fff;text-decoration:none;padding:11px 14px;border-radius:9px;font-weight:700}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.provider{background:#fff;border:1px solid #d7e7eb;border-radius:14px;padding:18px}.provider h3{margin:0 0 6px}.meta{font-size:14px;color:#617786}.pill{display:inline-block;background:#e7f5f6;color:#0b7180;padding:5px 8px;border-radius:999px;font-size:12px;font-weight:700}.small{font-size:13px;color:#617786}.provider a.button{display:inline-block;margin-top:10px;background:#087f91;color:#fff;text-decoration:none;padding:9px 12px;border-radius:8px;font-weight:700;font-size:13px}'''
def slug(s): return re.sub(r'[^a-z0-9]+','-',(s or '').lower()).strip('-')
def shell(title,desc,canonical,body,extra_ld=''):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title><meta name="description" content="{html.escape(desc)}"><link rel="canonical" href="{canonical}">{extra_ld}<style>{STYLE}</style></head><body><header>EazyMedicalTransportation.com is an independent directory and is not owned by or affiliated with any transportation provider listed on this site.</header><nav><a href="/">Home</a><a href="/browse/">Browse Providers</a><a href="/guides/">NEMT Guides</a><a href="/about/">About</a><a href="/data-sources/">Data Sources</a></nav><main>{body}</main><script src="/analytics-events.js?v=1" defer></script></body></html>'''
def guide_page(title,desc,sections,path):
    canonical=BASE+path
    crumbs={'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':BASE+'/'},{'@type':'ListItem','position':2,'name':'NEMT Guides','item':BASE+'/guides/'},{'@type':'ListItem','position':3,'name':title,'item':canonical}]}
    faq={'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':h,'acceptedAnswer':{'@type':'Answer','text':t}} for h,t in sections]}
    ld='<script type="application/ld+json">'+json.dumps([crumbs,faq],separators=(',',':')).replace('</','<\\/')+'</script>'
    cards=''.join(f'<section class="card"><h2>{html.escape(h)}</h2><p>{html.escape(t)}</p></section>' for h,t in sections)
    body=f'<p><a href="/guides/">NEMT Guides</a> › {html.escape(title)}</p><h1>{html.escape(title)}</h1><p>{html.escape(desc)}</p>{cards}<div class="links"><a href="/browse/" data-event="find_provider">Find Providers</a><a href="/non-emergency-medical-transportation/">What is NEMT?</a><a href="/guides/how-to-choose-a-nemt-provider/">Choose a Provider</a></div><p class="small">This guide is general information and does not establish insurance coverage, eligibility, medical necessity or provider availability.</p>'
    return shell(title+' | Eazy Medical Transportation',desc,canonical,body,ld)
def add_sitemap(urls):
    text=SITEMAP.read_text(encoding='utf-8')
    text=re.sub(r'\s*<url><loc>'+re.escape(BASE)+r'/(?:guides|browse|about|data-sources|listing-policy|editorial-policy)/.*?</url>','',text)
    block='\n'.join(f'  <url><loc>{BASE}{u}</loc><lastmod>2026-08-11</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>' for u in urls)
    SITEMAP.write_text(text.replace('</urlset>',block+'\n</urlset>'),encoding='utf-8')
def profile_map():
    p=ROOT/'providers/index.json'
    if not p.exists(): return {}
    return {str(x.get('npi')):x.get('url') for x in json.loads(p.read_text(encoding='utf-8'))}
def render_provider_card(p,abbr,profiles):
    npi=str(p.get('npi','')); url=profiles.get(npi)
    address=', '.join(x for x in [p.get('address1',''),p.get('city',''),abbr,p.get('zip','')] if x)
    tags=p.get('categories') or []
    taghtml=''.join(f'<span class="pill">{html.escape(t)}</span> ' for t in tags[:3])
    action=f'<a class="button" href="{url}" data-event="provider_profile_view">View Provider Profile</a>' if url else ''
    phone=f'<div class="meta">{html.escape(p.get("phone",""))}</div>' if p.get('phone') else ''
    return f'<article class="provider"><h3>{html.escape(p.get("name",""))}</h3><div class="meta">{html.escape(address)}</div>{phone}<div style="margin-top:8px">{taghtml}</div>{action}</article>'
def trust_pages(urls):
    pages={
      'about':('About EazyMedicalTransportation.com','Learn how EazyMedicalTransportation.com works as an independent directory for non-emergency medical transportation providers.', '<h1>About EazyMedicalTransportation.com</h1><p>EazyMedicalTransportation.com is an independent directory designed to help riders, families, care coordinators and healthcare organizations locate non-emergency medical transportation providers. The site does not operate transportation vehicles and is not owned by or affiliated with the providers listed.</p><div class="card"><h2>What Eazy does</h2><p>Eazy organizes public provider records into searchable location and provider pages, adds practical NEMT education, and gives providers a way to claim or update directory information.</p></div><div class="card"><h2>What Eazy does not do</h2><p>A listing is not an endorsement, guarantee of service, proof of insurance participation, or confirmation that a provider offers a specific ride type. Riders should verify details directly with the provider or applicable health plan.</p></div>'),
      'data-sources':('Provider Data Sources | Eazy Medical Transportation','Learn where Eazy provider information comes from and how directory records are maintained.', '<h1>Provider Data Sources</h1><p>The core provider directory is built from the CMS National Plan and Provider Enumeration System (NPPES) monthly data dissemination. Eazy focuses on active records carrying taxonomy code <strong>343900000X — Non-emergency Medical Transport (VAN)</strong>.</p><div class="card"><h2>What NPPES data can establish</h2><p>NPPES can identify an NPI record, organization name, practice-location information, telephone number when present, taxonomy and update dates.</p></div><div class="card"><h2>What NPPES data does not establish</h2><p>NPPES does not by itself prove current ride availability, wheelchair capability, dialysis service, insurance-network participation, pricing, licensing status beyond the NPI record, or service quality. Those details should be verified directly.</p></div>'),
      'listing-policy':('Provider Listing Policy | Eazy Medical Transportation','Read the Eazy policy for provider listings, corrections, claims and independent directory status.', '<h1>Provider Listing Policy</h1><p>Provider profiles may originate from public CMS NPPES records. Listing does not imply a commercial relationship with EazyMedicalTransportation.com.</p><div class="card"><h2>Claims and corrections</h2><p>Providers may use the Claim / Update This Profile process to submit corrections and richer service information. Submitted information should accurately describe the provider and may be reviewed before publication.</p></div><div class="card"><h2>Service claims</h2><p>Eazy avoids assigning service-specific claims such as wheelchair, dialysis or stretcher transportation unless there is explicit provider-supplied or otherwise reliable evidence supporting the classification.</p></div>'),
      'editorial-policy':('Editorial Policy | Eazy Medical Transportation','How Eazy prepares NEMT guides and separates general educational content from provider listings.', '<h1>Editorial Policy</h1><p>Eazy guides are intended to help users understand common non-emergency medical transportation questions and prepare to speak with providers, health plans and transportation brokers.</p><div class="card"><h2>General information</h2><p>Educational pages do not provide medical, insurance or legal advice and do not determine eligibility, coverage or medical necessity.</p></div><div class="card"><h2>Provider neutrality</h2><p>Directory inclusion is separate from editorial content. Eazy does not represent that one listed provider is superior to another merely because a profile appears in the directory.</p></div>')}
    for key,(title,desc,body) in pages.items():
        d=ROOT/key; d.mkdir(exist_ok=True); path=f'/{key}/'; (d/'index.html').write_text(shell(title,desc,BASE+path,body),encoding='utf-8'); urls.append(path)
def main():
    urls=[]; gd=ROOT/'guides'; gd.mkdir(exist_ok=True); cards=[]
    for key,(title,desc,sections) in GUIDES.items():
        path=f'/guides/{key}/'; d=ROOT/path.strip('/'); d.mkdir(parents=True,exist_ok=True); (d/'index.html').write_text(guide_page(title,desc,sections,path),encoding='utf-8'); urls.append(path); cards.append(f'<li><a href="{path}">{html.escape(title)}</a> — {html.escape(desc)}</li>')
    body=f'<h1>Non-Emergency Medical Transportation Guides</h1><p>Use these guides to understand transportation options, prepare for a ride and know what to ask independent providers.</p><ul>{"".join(cards)}</ul>'
    (gd/'index.html').write_text(shell('NEMT Guides | Eazy Medical Transportation','Practical guides to non-emergency medical transportation, wheelchair rides, dialysis transportation, Medicaid, Medicare and choosing a provider.',BASE+'/guides/',body),encoding='utf-8'); urls.append('/guides/')
    idx=json.loads((ROOT/'data/provider-index.json').read_text(encoding='utf-8')); profiles=profile_map(); rows=[]
    for s in idx['states']:
        rows.append(f'<li><a href="/browse/{s["abbr"].lower()}/">{html.escape(s["name"])}</a> — {s["providerCount"]:,} NPI-listed NEMT records</li>')
        sd=ROOT/'browse'/s['abbr'].lower(); sd.mkdir(parents=True,exist_ok=True); data=json.loads((ROOT/s['file']).read_text(encoding='utf-8'))
        orgs=[p for p in data.get('providers',[]) if str(p.get('entityType'))=='2']; city_counts=Counter((p.get('city') or '').title() for p in orgs if p.get('city'))
        topcities=''.join(f'<li>{html.escape(c)} — {n} organization records</li>' for c,n in city_counts.most_common(10)); cards=''.join(render_provider_card(p,s['abbr'],profiles) for p in orgs[:75])
        path=f'/browse/{s["abbr"].lower()}/'; body=f'<h1>Non-Emergency Medical Transportation in {html.escape(s["name"])}</h1><p>The Eazy directory currently contains {s["providerCount"]:,} active NPPES records in {html.escape(s["name"])} carrying the Non-emergency Medical Transport (VAN) taxonomy.</p><div class="card"><h2>Major provider cities in the directory</h2><ul>{topcities}</ul></div><h2>Provider organizations</h2><div class="grid">{cards}</div><p class="small">Verify current services, coverage, accessibility and availability directly with each provider.</p>'
        (sd/'index.html').write_text(shell(f'Non-Emergency Medical Transportation Providers in {s["name"]} | Eazy',f'Browse independent NPI-listed non-emergency medical transportation organizations in {s["name"]}.',BASE+path,body),encoding='utf-8'); urls.append(path)
    il=json.loads((ROOT/'data/providers/IL.json').read_text(encoding='utf-8')); il_orgs=[p for p in il.get('providers',[]) if str(p.get('entityType'))=='2']
    for city in PRIORITY_CITIES:
        city_providers=[p for p in il_orgs if (p.get('city') or '').upper()==city]
        if not city_providers: continue
        cslug=slug(city); path=f'/browse/il/{cslug}/'; d=ROOT/path.strip('/'); d.mkdir(parents=True,exist_ok=True)
        cards=''.join(render_provider_card(p,'IL',profiles) for p in city_providers[:100]); title=city.title()
        body=f'<p><a href="/browse/il/">Illinois</a> › {html.escape(title)}</p><h1>NEMT Providers in {html.escape(title)}, Illinois</h1><p>Browse {len(city_providers)} NPPES organization records in {html.escape(title)} carrying the Non-emergency Medical Transport (VAN) taxonomy.</p><div class="grid">{cards}</div><p class="small">A directory record is not confirmation of current service availability or a specific transportation capability.</p>'
        (d/'index.html').write_text(shell(f'NEMT Providers in {title}, IL | Eazy',f'Browse NPI-listed non-emergency medical transportation organizations in {title}, Illinois.',BASE+path,body),encoding='utf-8'); urls.append(path)
    bd=ROOT/'browse'; bd.mkdir(exist_ok=True); body=f'<h1>Browse Non-Emergency Medical Transportation Providers by State</h1><p>Choose a state to browse active NPPES records carrying the Non-emergency Medical Transport (VAN) taxonomy.</p><ul>{"".join(rows)}</ul>'
    (bd/'index.html').write_text(shell('Browse NEMT Providers by State | Eazy Medical Transportation','Browse non-emergency medical transportation provider records by state across the United States.',BASE+'/browse/',body),encoding='utf-8'); urls.append('/browse/')
    trust_pages(urls); add_sitemap(urls); print('Generated',len(GUIDES),'guides,',len(idx['states']),'state pages, Illinois city pages and trust pages')
if __name__=='__main__': main()
