#!/usr/bin/env python3
import json,re,html
from pathlib import Path
ROOT=Path('.')
BASE='https://eazymedicaltransportation.com'
SITEMAP=ROOT/'sitemap.xml'
GUIDES={
'how-nemt-works':('How Non-Emergency Medical Transportation Works','A practical explanation of NEMT, who uses it, how trips are arranged, and what riders should confirm before scheduling.',[('What NEMT is','Non-emergency medical transportation helps people reach scheduled healthcare when an ambulance is not required. Trips may include physician visits, dialysis, therapy, outpatient procedures and other planned care.'),('How rides are arranged','Depending on the rider and payer, transportation may be arranged directly with a provider, through a managed-care plan, transportation broker, facility, caregiver or private-pay booking.'),('What to confirm','Confirm pickup location, appointment time, mobility needs, return-trip procedure, service area, payment arrangements and whether an escort or special assistance is required.')]),
'medicaid-nemt-guide':('Medicaid and Non-Emergency Medical Transportation','Understand how Medicaid transportation commonly works and what information riders should verify with their plan or transportation provider.',[('Coverage varies','Medicaid transportation rules and scheduling procedures vary by state and managed-care plan. Riders should confirm eligibility and authorization requirements with the applicable program.'),('Plan ahead','Recurring treatments and long-distance trips may require advance scheduling. Keep appointment details, member information and mobility needs available when arranging transportation.'),('Provider verification','A directory listing does not establish Medicaid participation. Confirm network status and authorization directly with the plan, broker or provider.')]),
'medicare-transportation-guide':('Medicare Transportation: What to Know','A plain-language guide to Medicare transportation, Medicare Advantage transportation benefits and the difference from Medicaid NEMT.',[('Traditional Medicare','Routine non-emergency rides are not generally a standard Original Medicare transportation benefit. Coverage circumstances differ from emergency or medically necessary ambulance services.'),('Medicare Advantage','Some Medicare Advantage plans may include transportation benefits. The member should verify limits, eligible destinations and scheduling procedures with the plan.'),('Do not assume coverage','Before booking, ask who is responsible for payment and whether prior authorization or use of a designated transportation network is required.')]),
'wheelchair-transportation-guide':('Wheelchair Transportation Guide','How to compare wheelchair-accessible NEMT providers and prepare for a medical transportation trip.',[('Vehicle fit','Tell the provider the wheelchair type, approximate dimensions, passenger weight if relevant, and whether the rider can transfer from the chair.'),('Assistance level','Ask whether service is curb-to-curb, door-to-door or includes additional assistance. Explain stairs, ramps, elevators and oxygen or equipment needs.'),('Return trips','Medical appointments may run late. Confirm how return pickups are handled and who to contact if the appointment schedule changes.')]),
'dialysis-transportation-guide':('Dialysis Transportation Guide','How to plan recurring transportation to dialysis and reduce missed or delayed trips.',[('Recurring schedules','Dialysis often occurs multiple times each week, making consistent pickup windows and provider communication especially important.'),('Treatment end times','Return times can vary. Ask whether the provider waits, uses a will-call return, or schedules a flexible pickup window.'),('Backup planning','Keep provider and facility contact information available and understand the procedure if a driver is delayed or a treatment schedule changes.')]),
'hospital-discharge-transportation':('Hospital Discharge Transportation','What families and care teams should consider when arranging non-emergency transportation after a hospital discharge.',[('Match the vehicle to the patient','Confirm whether the passenger can walk, needs a wheelchair-accessible vehicle, requires a stretcher-capable service or needs other assistance.'),('Coordinate timing','Discharge times can shift. Confirm how the provider handles delays and whether the facility requires a specific pickup location.'),('Destination readiness','Make sure someone can receive the passenger if needed and that stairs, ramps, elevators or mobility equipment at the destination are considered.')]),
'how-to-choose-a-nemt-provider':('How to Choose a Non-Emergency Medical Transportation Provider','Questions to ask when comparing NEMT providers for yourself, a family member or a patient.',[('Service area and trip type','Confirm that the provider serves both the pickup and destination and can handle one-time or recurring trips.'),('Accessibility','Describe mobility needs in detail and verify the vehicle and assistance level before scheduling.'),('Payment and scheduling','Ask about rates or benefits, cancellation rules, scheduling lead time, return-trip procedures and how to reach dispatch on the day of travel.')]),
'private-pay-medical-transportation':('Private-Pay Medical Transportation','When private-pay NEMT may be useful and what to ask before paying for a ride.',[('When it is used','Families may choose private-pay transportation when insurance does not cover the trip, when a preferred provider is out of network, or when a faster scheduling option is needed.'),('Get the full price','Ask whether the quote includes mileage, wait time, wheelchair service, assistance, tolls and the return trip.'),('Confirm cancellation terms','Understand deposits, cancellation windows and charges if an appointment runs longer than expected.')]),
'recurring-medical-rides':('Recurring Medical Transportation','A guide to organizing repeat rides for dialysis, therapy, rehabilitation and other ongoing care.',[('Create a master schedule','Provide treatment days, appointment times, pickup address, facility address and any recurring mobility needs.'),('Use consistent contacts','Keep the same rider, caregiver, facility and dispatch contact information whenever possible.'),('Review changes','Reconfirm holidays, treatment schedule changes and transportation authorizations before they become missed trips.')]),
'nemt-checklist':('NEMT Ride Scheduling Checklist','A simple checklist of information to have ready before contacting a medical transportation provider.',[('Trip details','Pickup address, destination, appointment date and time, one-way or round-trip status and expected return timing.'),('Passenger needs','Wheelchair or ambulatory status, transfer ability, stairs, oxygen or equipment, escort needs and any assistance requirements.'),('Payment details','Insurance or plan information when applicable, authorization number if required, or private-pay pricing and payment method.')])}
STYLE='''body{margin:0;font-family:Arial,sans-serif;color:#153a56;background:#f7fbfc}header{background:#087f91;color:#fff;text-align:center;padding:11px 18px;font-weight:700;font-size:13px}nav{background:#fff;border-bottom:1px solid #d7e7eb;padding:18px 6%;display:flex;gap:24px;flex-wrap:wrap}nav a{color:#0b3552;text-decoration:none;font-weight:700}main{max-width:930px;margin:auto;padding:48px 22px 70px}h1{font-size:42px;line-height:1.08;margin:0 0 16px}h2{margin-top:34px}p,li{font-size:17px;line-height:1.7;color:#4c6676}.card{background:#fff;border:1px solid #d7e7eb;border-radius:16px;padding:24px;margin:22px 0}.links{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.links a{background:#087f91;color:#fff;text-decoration:none;padding:11px 14px;border-radius:9px;font-weight:700}'''
def slug(s): return re.sub(r'[^a-z0-9]+','-',s.lower()).strip('-')
def page(title,desc,sections,path):
    canonical=BASE+path
    crumbs=json.dumps({'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':BASE+'/'},{'@type':'ListItem','position':2,'name':'NEMT Guides','item':BASE+'/guides/'},{'@type':'ListItem','position':3,'name':title,'item':canonical}]},separators=(',',':'))
    body=''.join(f'<section class="card"><h2>{html.escape(h)}</h2><p>{html.escape(t)}</p></section>' for h,t in sections)
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} | Eazy Medical Transportation</title><meta name="description" content="{html.escape(desc)}"><link rel="canonical" href="{canonical}"><script type="application/ld+json">{crumbs}</script><style>{STYLE}</style></head><body><header>EazyMedicalTransportation.com is an independent directory and is not owned by or affiliated with any transportation provider listed on this site.</header><nav><a href="/">Home</a><a href="/browse/">Browse Providers</a><a href="/guides/">NEMT Guides</a><a href="/wheelchair-transportation/">Wheelchair</a><a href="/dialysis-transportation/">Dialysis</a></nav><main><p><a href="/guides/">NEMT Guides</a> › {html.escape(title)}</p><h1>{html.escape(title)}</h1><p>{html.escape(desc)}</p>{body}<div class="links"><a href="/browse/">Find Providers</a><a href="/non-emergency-medical-transportation/">What is NEMT?</a><a href="/guides/how-to-choose-a-nemt-provider/">Choose a Provider</a></div><p style="margin-top:28px;font-size:13px">This guide is general information and does not establish insurance coverage, eligibility, medical necessity or provider availability.</p></main></body></html>'''
def add_sitemap(urls):
    text=SITEMAP.read_text(encoding='utf-8')
    text=re.sub(r'\s*<url><loc>'+re.escape(BASE)+r'/(?:guides|browse)/.*?</url>','',text)
    block='\n'.join(f'  <url><loc>{BASE}{u}</loc><lastmod>2026-08-11</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>' for u in urls)
    SITEMAP.write_text(text.replace('</urlset>',block+'\n</urlset>'),encoding='utf-8')
def main():
    urls=[]; gd=ROOT/'guides'; gd.mkdir(exist_ok=True)
    cards=[]
    for key,(title,desc,sections) in GUIDES.items():
        path=f'/guides/{key}/'; d=ROOT/path.strip('/'); d.mkdir(parents=True,exist_ok=True); (d/'index.html').write_text(page(title,desc,sections,path),encoding='utf-8'); urls.append(path); cards.append(f'<li><a href="{path}">{html.escape(title)}</a> — {html.escape(desc)}</li>')
    (gd/'index.html').write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NEMT Guides | Eazy Medical Transportation</title><meta name="description" content="Practical guides to non-emergency medical transportation, wheelchair rides, dialysis transportation, Medicaid, Medicare and choosing a provider."><link rel="canonical" href="{BASE}/guides/"><style>{STYLE}</style></head><body><header>EazyMedicalTransportation.com is an independent directory and is not owned by or affiliated with any transportation provider listed on this site.</header><nav><a href="/">Home</a><a href="/browse/">Browse Providers</a><a href="/guides/">NEMT Guides</a></nav><main><h1>Non-Emergency Medical Transportation Guides</h1><p>Use these guides to understand transportation options, prepare for a ride and know what to ask independent providers.</p><ul>{''.join(cards)}</ul></main></body></html>''',encoding='utf-8'); urls.append('/guides/')
    idx=json.loads((ROOT/'data/provider-index.json').read_text(encoding='utf-8')); rows=[]
    for s in idx['states']:
        rows.append(f'<li><a href="/browse/{s["abbr"].lower()}/">{html.escape(s["name"])}</a> — {s["providerCount"]:,} NPI-listed NEMT records</li>')
        sd=ROOT/'browse'/s['abbr'].lower(); sd.mkdir(parents=True,exist_ok=True)
        data=json.loads((ROOT/s['file']).read_text(encoding='utf-8')); orgs=[p for p in data.get('providers',[]) if str(p.get('entityType'))=='2'][:75]
        items=''.join(f'<li><strong>{html.escape(p.get("name",""))}</strong> — {html.escape(p.get("city",""))}, {s["abbr"]}</li>' for p in orgs)
        path=f'/browse/{s["abbr"].lower()}/'; (sd/'index.html').write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Non-Emergency Medical Transportation Providers in {html.escape(s['name'])} | Eazy</title><meta name="description" content="Browse independent NPI-listed non-emergency medical transportation organizations in {html.escape(s['name'])}."><link rel="canonical" href="{BASE}{path}"><style>{STYLE}</style></head><body><header>EazyMedicalTransportation.com is an independent directory and is not owned by or affiliated with any transportation provider listed on this site.</header><nav><a href="/">Home</a><a href="/browse/">All States</a><a href="/guides/">NEMT Guides</a></nav><main><h1>Non-Emergency Medical Transportation in {html.escape(s['name'])}</h1><p>The Eazy directory currently contains {s['providerCount']:,} active NPPES records in {html.escape(s['name'])} carrying the Non-emergency Medical Transport (VAN) taxonomy. The list below highlights organization records from the directory. Verify services and availability directly with each provider.</p><ul>{items}</ul></main></body></html>''',encoding='utf-8'); urls.append(path)
    bd=ROOT/'browse'; bd.mkdir(exist_ok=True); (bd/'index.html').write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Browse NEMT Providers by State | Eazy Medical Transportation</title><meta name="description" content="Browse non-emergency medical transportation provider records by state across the United States."><link rel="canonical" href="{BASE}/browse/"><style>{STYLE}</style></head><body><header>EazyMedicalTransportation.com is an independent directory and is not owned by or affiliated with any transportation provider listed on this site.</header><nav><a href="/">Home</a><a href="/browse/">Browse Providers</a><a href="/guides/">NEMT Guides</a></nav><main><h1>Browse Non-Emergency Medical Transportation Providers by State</h1><p>Choose a state to browse active NPPES records carrying the Non-emergency Medical Transport (VAN) taxonomy.</p><ul>{''.join(rows)}</ul></main></body></html>''',encoding='utf-8'); urls.append('/browse/')
    add_sitemap(urls); print('Generated',len(GUIDES),'guides and',len(idx['states']),'state browse pages')
if __name__=='__main__': main()
